## Task 2

In [ ]:
#Reading and Writing from a file.
#reading a file
f1 = open("/content/File1.txt",'r')
print(f1.read())

This is the first file .
Python is a powerful language with easy syntax
Coding improves mental health .
Reminder to drink water.


In [ ]:
f1.close()

In [ ]:
#writing the contents of a file
f2 = open("/content/sample_text1.txt", 'r')
print(f2.read())

I will now make changes in the contents of the file/n


In [ ]:
f2.close()

In [ ]:
f2 = open("/content/sample_text1.txt", 'w')

In [ ]:
f2.write('I will now make changes in the contents of the file/n',)
f2.close()

In [ ]:
f2 = open("/content/sample_text1.txt", 'r')


In [ ]:
print(f2.read())

I will now make changes in the contents of the file/n


In [ ]:
f2.close()

In [ ]:
# to find out the file size
import os

In [ ]:
file_name ="/content/sample_text2.txt"

file_stats = os.stat(file_name)

print(file_stats)
print(f'File Size in Bytes is {file_stats.st_size}')

os.stat_result(st_mode=33188, st_ino=4587621, st_dev=53, st_nlink=1, st_uid=0, st_gid=0, st_size=100, st_atime=1711981138, st_mtime=1711981122, st_ctime=1711981122)
File Size in Bytes is 100


In [ ]:
#to find out the most frequent word
from collections import Counter
with open("/content/sample_text2.txt", 'r') as file_1:
   text = file_1.read().lower()
   words = text.split()
   word_counts = Counter(words)
   most_common_word, frequency = word_counts.most_common(1)[0]
print(f"The most frequent word is '{most_common_word}' with frequency {frequency}.")
file_1.close()

The most frequent word is 'python' with frequency 5.


In [ ]:
# to get a specific line from a file
file1=open("/content/sample_text2.txt","r")
content=file1.readlines()
file1.close()
index=int(input("Enter the line number to read:"))
print(content[index-1])


Enter the line number to read:4
python python python python


In [ ]:
#loading a json file in python
import json

f = open('/content/sample.json')

data = json.load(f)

print(data)

f.close()


{'name': 'Harsh Martin Topno', 'rollno': 2306187, 'language': 'Python'}


In [ ]:
dictionary = {
    "name": "Harsh Martin Topno",
    "rollno": 2306187,
    "language": "Python"
}

with open("sample.json", "w") as outfile:
    json.dump(dictionary, outfile)

f = open('/content/sample.json')
data = json.load(f)

print(data)

f.close()

{'name': 'Harsh Martin Topno', 'rollno': 2306187, 'language': 'Python'}


## Task 3

In [ ]:
#Create an empty and a full NumPy array
import numpy as np

In [ ]:
empty_arr = np.empty((3,3,3))
print(empty_arr)

[[[ 5.03922454e-310  0.00000000e+000  6.71444416e-310]
  [-1.39620736e-080  6.71444421e-310  6.71444416e-310]
  [-4.59020089e-295  6.71444421e-310  6.71444416e-310]]

 [[ 7.16395186e-322  5.03981824e-310  6.71446492e-310]
  [ 4.47593816e-091  6.14735849e+223  1.92864608e+199]
  [ 4.46829593e-091  1.75629761e-152  1.23811212e+223]]

 [[ 7.22762267e+159  5.81996278e+257  9.52668386e+077]
  [ 4.78713095e+180  1.81434271e-152  8.25148021e-154]
  [ 3.30426893e-033  1.33440016e-317  1.89721208e-321]]]


In [ ]:
full_arr = np.full((3,3,3),24)
print(full_arr)

[[[24 24 24]
  [24 24 24]
  [24 24 24]]

 [[24 24 24]
  [24 24 24]
  [24 24 24]]

 [[24 24 24]
  [24 24 24]
  [24 24 24]]]


In [ ]:
#Create a Numpy array filled with all zeros
arr_0 = np.zeros((3,4,3))
print(arr_0)

[[[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]]


In [ ]:
#Create a Numpy array filled with all ones
arr_1 = np.ones((4,3,4))
print(arr_1)

[[[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]

 [[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]

 [[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]

 [[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]]


In [ ]:
# Replace NumPy array elements that don’t satisfy a given condition
array = np.random.randint(50, size=(4,4,4))
print(array)

[[[ 0  8  2  6]
  [27 43 36 36]
  [31 13 18 25]
  [ 3 45 40 10]]

 [[46 34 14  9]
  [ 6 18 15 33]
  [38 13 12  3]
  [28 12 17 11]]

 [[11 48 29 24]
  [20 30 48 13]
  [29 21 18 10]
  [ 6 30 25 23]]

 [[23 28 10 42]
  [30 42  9  0]
  [ 7 37  8 19]
  [ 5 42 17 23]]]


In [ ]:
array.shape

(4, 4, 4)

In [ ]:
print("Array before checking the condition\n")
print(array)

for i in range(4):
  for j in range(4):
    for k in range(4):
      if array[i,j,k]%2 == 0:
        pass
      else:
        array[i,j,k] = 0

print("\nArray after checking the condition and replacing the values\n")
print(array)




Array before checking the condition

[[[ 0  8  2  6]
  [27 43 36 36]
  [31 13 18 25]
  [ 3 45 40 10]]

 [[46 34 14  9]
  [ 6 18 15 33]
  [38 13 12  3]
  [28 12 17 11]]

 [[11 48 29 24]
  [20 30 48 13]
  [29 21 18 10]
  [ 6 30 25 23]]

 [[23 28 10 42]
  [30 42  9  0]
  [ 7 37  8 19]
  [ 5 42 17 23]]]

Array after checking the condition and replacing the values

[[[ 0  8  2  6]
  [ 0  0 36 36]
  [ 0  0 18  0]
  [ 0  0 40 10]]

 [[46 34 14  0]
  [ 6 18  0  0]
  [38  0 12  0]
  [28 12  0  0]]

 [[ 0 48  0 24]
  [20 30 48  0]
  [ 0  0 18 10]
  [ 6 30  0  0]]

 [[ 0 28 10 42]
  [30 42  0  0]
  [ 0  0  8  0]
  [ 0 42  0  0]]]


In [ ]:
#Get the maximum value from a matrix
array = np.random.randint(50, size=(4,4,4))
print(array)
print(f"\nThe maximum value of the matrix is: {array.max()} ")

[[[16 40 16 41]
  [20  7 36 46]
  [48 49 22 30]
  [32 42 35  9]]

 [[37 11 35  9]
  [19 29 22 41]
  [31 39 32  1]
  [46 49 19 28]]

 [[18 47  7 45]
  [43 20 47 27]
  [ 1 20  1  7]
  [13 16 39 38]]

 [[20 13 32 48]
  [25 22 38 19]
  [39 45 41 49]
  [15 15 44 25]]]

The maximum value of the matrix is: 49 


## Task 4

In [ ]:
#Using dataset- "Historical NBA Finals and MVP Results" from Kaggle
import pandas as pd

In [ ]:
data = pd.read_csv("/content/archive (6).zip")

In [ ]:
data.head()

index  Year    Western Champion    Eastern Champion Result  \
0      0  1950  Minneapolis Lakers  Syracuse Nationals    4–2   
1      1  1951    Rochester Royals     New York Knicks    4–3   
2      2  1952  Minneapolis Lakers     New York Knicks    4–3   
3      3  1953  Minneapolis Lakers     New York Knicks    4–1   
4      4  1954  Minneapolis Lakers  Syracuse Nationals    4–3   

         NBA Champion   NBA Vice-Champion  Final Sweep ? MVP Name  \
0  Minneapolis Lakers  Syracuse Nationals          False      NaN   
1    Rochester Royals     New York Knicks          False      NaN   
2  Minneapolis Lakers     New York Knicks          False      NaN   
3  Minneapolis Lakers     New York Knicks          False      NaN   
4  Minneapolis Lakers  Syracuse Nationals          False      NaN   

   MVP Height (m)  MVP Height (ft) MVP Position MVP Team MVP Nationality  \
0             NaN              NaN          NaN      NaN             NaN   
1             NaN              NaN          NaN      NaN             NaN   
2             NaN              NaN          NaN      NaN             NaN   
3             NaN              NaN          NaN      NaN             NaN   
4             NaN              NaN          NaN      NaN             NaN   

  MVP status  
0        NaN  
1        NaN  
2        NaN  
3        NaN  
4        NaN

In [ ]:
data.drop(['index'],axis = 1, inplace = True)

In [ ]:
#Split a column in Pandas dataframe and get part of it

In [ ]:
data['MVP Nationality'].unique()

array([nan, 'US', 'Nigeria', 'Canada', 'Germany'], dtype=object)

In [ ]:
data[["West_Game_win",'East_Game_win']] = data['Result'].str.split("–",n=1,expand= True)

In [ ]:
data.head()

Year    Western Champion    Eastern Champion Result        NBA Champion  \
0  1950  Minneapolis Lakers  Syracuse Nationals    4–2  Minneapolis Lakers   
1  1951    Rochester Royals     New York Knicks    4–3    Rochester Royals   
2  1952  Minneapolis Lakers     New York Knicks    4–3  Minneapolis Lakers   
3  1953  Minneapolis Lakers     New York Knicks    4–1  Minneapolis Lakers   
4  1954  Minneapolis Lakers  Syracuse Nationals    4–3  Minneapolis Lakers   

    NBA Vice-Champion  Final Sweep ? MVP Name  MVP Height (m)  \
0  Syracuse Nationals          False      NaN             NaN   
1     New York Knicks          False      NaN             NaN   
2     New York Knicks          False      NaN             NaN   
3     New York Knicks          False      NaN             NaN   
4  Syracuse Nationals          False      NaN             NaN   

   MVP Height (ft) MVP Position MVP Team MVP Nationality MVP status  \
0              NaN          NaN      NaN             NaN        NaN   
1              NaN          NaN      NaN             NaN        NaN   
2              NaN          NaN      NaN             NaN        NaN   
3              NaN          NaN      NaN             NaN        NaN   
4              NaN          NaN      NaN             NaN        NaN   

  West_Game_win East_Game_win  
0             4             2  
1             4             3  
2             4             3  
3             4             1  
4             4             3

In [ ]:
data.tail()

Year       Western Champion     Eastern Champion Result  \
64  2014      San Antonio Spurs           Miami Heat    4–1   
65  2015  Golden State Warriors  Cleveland Cavaliers    4–2   
66  2016  Golden State Warriors  Cleveland Cavaliers    4–3   
67  2017  Golden State Warriors  Cleveland Cavaliers    4-2   
68  2018  Golden State Warriors  Cleveland Cavaliers    4-0   

             NBA Champion      NBA Vice-Champion  Final Sweep ?      MVP Name  \
64      San Antonio Spurs             Miami Heat          False     K. Durant   
65  Golden State Warriors    Cleveland Cavaliers          False      S. Curry   
66    Cleveland Cavaliers  Golden State Warriors          False      S. Curry   
67  Golden State Warriors    Cleveland Cavaliers          False  R. Westbrook   
68  Golden State Warriors    Cleveland Cavaliers           True     J. Harden   

    MVP Height (m)  MVP Height (ft) MVP Position               MVP Team  \
64            2.06         6.758530      Forward  Oklahoma City Thunder   
65            1.91         6.266404        Guard  Golden State Warriors   
66            1.91         6.266404        Guard  Golden State Warriors   
67            1.91         6.266404        Guard  Oklahoma City Thunder   
68            1.96         6.500000        Guard        Houston Rockets   

   MVP Nationality         MVP status West_Game_win East_Game_win  
64              US  Not reached Final             4             1  
65              US           Champion             4             2  
66              US      Vice-Champion             4             3  
67              US  Not reached Final           4-2          None  
68              US  Not reached Final           4-0          None

In [ ]:
data[["West_Game_win",'East_Game_win']]

West_Game_win East_Game_win
0              4             2
1              4             3
2              4             3
3              4             1
4              4             3
..           ...           ...
64             4             1
65             4             2
66             4             3
67           4-2          None
68           4-0          None

[69 rows x 2 columns]

In [ ]:
#Return the Index label if some condition is satisfied over a column in Pandas Dataframe
#condition: show the rows labels for those columns whose year is divisible by 4
count = 0
for year in data['Year']:

  if year%4 == 0 :
    print(data.index[count])
    count += 1
  else:
    count += 1

2
6
10
14
18
22
26
30
34
38
42
46
50
54
58
62
66


In [ ]:
#Drop rows from the dataframe based on certain condition applied on a column
#condition:dropping all the rows where the MVP is from US
data
count = 0
for i in data['MVP Nationality']:

  if i == 'US' :
    data.drop(count,inplace = True)
    count += 1
  else:
    count += 1




In [ ]:
data

Year    Western Champion     Eastern Champion Result        NBA Champion  \
0   1950  Minneapolis Lakers   Syracuse Nationals    4–2  Minneapolis Lakers   
1   1951    Rochester Royals      New York Knicks    4–3    Rochester Royals   
2   1952  Minneapolis Lakers      New York Knicks    4–3  Minneapolis Lakers   
3   1953  Minneapolis Lakers      New York Knicks    4–1  Minneapolis Lakers   
4   1954  Minneapolis Lakers   Syracuse Nationals    4–3  Minneapolis Lakers   
5   1955  Fort Wayne Pistons   Syracuse Nationals    3–4  Syracuse Nationals   
44  1994     Houston Rockets      New York Knicks    4–3     Houston Rockets   
55  2005   San Antonio Spurs      Detroit Pistons    4–3   San Antonio Spurs   
56  2006    Dallas Mavericks           Miami Heat    2–4          Miami Heat   
57  2007   San Antonio Spurs  Cleveland Cavaliers    4–0   San Antonio Spurs   

      NBA Vice-Champion  Final Sweep ?     MVP Name  MVP Height (m)  \
0    Syracuse Nationals          False          NaN             NaN   
1       New York Knicks          False          NaN             NaN   
2       New York Knicks          False          NaN             NaN   
3       New York Knicks          False          NaN             NaN   
4    Syracuse Nationals          False          NaN             NaN   
5    Fort Wayne Pistons          False          NaN             NaN   
44      New York Knicks          False  H. Olajuwon            2.13   
55      Detroit Pistons          False      S. Nash            1.91   
56     Dallas Mavericks          False      S. Nash            1.91   
57  Cleveland Cavaliers           True  D. Nowitzki            2.13   

    MVP Height (ft) MVP Position          MVP Team MVP Nationality  \
0               NaN          NaN               NaN             NaN   
1               NaN          NaN               NaN             NaN   
2               NaN          NaN               NaN             NaN   
3               NaN          NaN               NaN             NaN   
4               NaN          NaN               NaN             NaN   
5               NaN          NaN               NaN             NaN   
44         6.988189       Center   Houston Rockets         Nigeria   
55         6.266404        Guard      Phoenix Suns          Canada   
56         6.266404        Guard      Phoenix Suns          Canada   
57         6.988189      Forward  Dallas Mavericks         Germany   

           MVP status West_Game_win East_Game_win  
0                 NaN             4             2  
1                 NaN             4             3  
2                 NaN             4             3  
3                 NaN             4             1  
4                 NaN             4             3  
5                 NaN             3             4  
44           Champion             4             3  
55  Not reached Final             4             3  
56  Not reached Final             2             4  
57  Not reached Final             4             0

## Task 5

In [ ]:
#How to get list of parameters name from a function in Python

In [ ]:
def my_func(a,b,c,d):
  pass


In [ ]:
import inspect

In [ ]:
#to get the parameters list of an explicit function
print(inspect.signature(my_func))

(a, b, c, d)


In [ ]:
#to get the parameters list of an in-built function
print(inspect.signature(list))

(iterable=(), /)


In [ ]:
#How to Print Multiple Arguments in Python?

In [ ]:
#for known number of arguments
#there are multiple ways to this
def my_func(argument1,argument2,argument3):
  print("The arguments provided by the user are: {a}, {b}, {c}".format(a = argument1, b = argument2, c = argument3))
  #or we can use f-string
  print(f"The arguments provided by the user are: {argument1}, {argument2}, {argument3}")

In [ ]:
my_func('Harsh Martin Topno', 18,"CSE")

The arguments provided by the user are: Harsh Martin Topno, 18, CSE
The arguments provided by the user are: Harsh Martin Topno, 18, CSE


In [ ]:
#for unknown number of arguments
def func_to_print(*args):
  print("The arguments given by the user are:")
  for i in args:
    print(i)


In [ ]:
func_to_print('Harsh Martin Topno', 18)

The arguments given by the user are:
Harsh Martin Topno
18


In [ ]:
#Python program to find the power of a number using recursion
def power(number,p):
  if p == 0:
    return 1
  elif p > 0:
    return (number * power(number,p-1))
  else:
    return (1/number * power(number,p+1))


In [ ]:
power(6,9)

10077696

In [ ]:
power(6,-5)

0.00012860082304526747