In [1]:
import numpy as np

In [15]:
arr1=np.array([1,2,3,4,5,6])
#To create a full array of specific shape and fill with a specific value
arr3=np.full(shape=(3,3),fill_value=7)

In [3]:
arr1

array([1, 2, 3, 4, 5, 6])

In [16]:
arr3

array([[7, 7, 7],
       [7, 7, 7],
       [7, 7, 7]])

In [10]:
type(arr1)

numpy.ndarray

In [13]:
arr2=np.empty((1,6),)

In [19]:
arr2 #filled with random values

array([[2.7210493e-316, 0.0000000e+000, 5.8025718e-317, 5.8025718e-317,
        5.7635959e-317, 5.7754337e-317]])

In [20]:
arr4=np.zeros((3,3))
arr5=np.ones((3,3))

In [23]:
arr4 #default data type is float can change it

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [22]:
arr5

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [29]:
arr6=np.where(arr1>3,arr1,0)
arr6
#It keeps the arr elements that satisfies the given condtions and replaces the ones that don't satisfy with zero .. much like the ternary function

array([0, 0, 0, 4, 5, 6])

In [31]:
arr7=arr1.reshape((2,3))
arr7

array([[1, 2, 3],
       [4, 5, 6]])

In [32]:
np.max(arr7)
#To get maximum value of a matrix

6