<a href="https://colab.research.google.com/github/Ankita-3012/Gray-Interface-Tasks/blob/ankita1/Task3_Ankita.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

*Full and Empty arrays using numpy

In [1]:
import pandas as pd
import numpy as np

In [11]:
empty_arr = np.empty((2,3), dtype=int)

In [6]:
full_arr = np.full([2,3], 34, dtype=int)

In [12]:
empty_arr

array([[   101318861438520,                  0,    101309159370800],
       [   138379481332992, 244573554082072932, -63049252238000045]])

In [8]:
print(full_arr)

[[34 34 34]
 [34 34 34]]


In [14]:
df = pd.read_csv('/content/archive (1).zip')

In [38]:
df.head()

PassengerId  Survived  Pclass  \
0          892         0       3   
1          893         1       3   
2          894         0       2   
3          895         0       3   
4          896         1       3   

                                           Name     Sex   Age  SibSp  Parch  \
0                              Kelly, Mr. James    male  34.5      0      0   
1              Wilkes, Mrs. James (Ellen Needs)  female  47.0      1      0   
2                     Myles, Mr. Thomas Francis    male  62.0      0      0   
3                              Wirz, Mr. Albert    male  27.0      0      0   
4  Hirvonen, Mrs. Alexander (Helga E Lindqvist)  female  22.0      1      1   

    Ticket     Fare Cabin Embarked  
0   330911   7.8292   NaN        Q  
1   363272   7.0000   NaN        S  
2   240276   9.6875   NaN        Q  
3   315154   8.6625   NaN        S  
4  3101298  12.2875   NaN        S

In [39]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 418 entries, 0 to 417
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype  
---  ------       --------------  -----  
 0   PassengerId  418 non-null    int64  
 1   Survived     418 non-null    int64  
 2   Pclass       418 non-null    int64  
 3   Name         418 non-null    object 
 4   Sex          418 non-null    object 
 5   Age          332 non-null    float64
 6   SibSp        418 non-null    int64  
 7   Parch        418 non-null    int64  
 8   Ticket       418 non-null    object 
 9   Fare         417 non-null    float64
 10  Cabin        91 non-null     object 
 11  Embarked     418 non-null    object 
dtypes: float64(2), int64(5), object(5)
memory usage: 39.3+ KB


In [40]:
df.drop(['Name', 'Sex', 'Cabin', 'Embarked'], axis=1, inplace=True)

In [43]:
df.drop(['Age'], axis=1, inplace=True)

In [47]:
df['Fare'].fillna(df['Fare'].mode()[0], inplace=True)

In [52]:
df.drop(['Ticket'], axis=1, inplace= True)

In [54]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 418 entries, 0 to 417
Data columns (total 6 columns):
 #   Column       Non-Null Count  Dtype  
---  ------       --------------  -----  
 0   PassengerId  418 non-null    int64  
 1   Survived     418 non-null    int64  
 2   Pclass       418 non-null    int64  
 3   SibSp        418 non-null    int64  
 4   Parch        418 non-null    int64  
 5   Fare         418 non-null    float64
dtypes: float64(1), int64(5)
memory usage: 19.7 KB


In [70]:
np_df = df.to_numpy()

In [56]:
full_arr= np.full_like(np_df, fill_value=1)

In [57]:
empty_arr = np.empty_like(np_df)

In [59]:
print('Shape of empty array:', empty_arr.shape)

Shape of empty array: (418, 6)


In [60]:
print('Shape of full array:', full_arr.shape)

Shape of full array: (418, 6)


*Numpy array filled with all zeros

In [21]:
arr = np.full([3,4], 0, dtype=int)

In [22]:
arr

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

In [61]:
np_df = df.to_numpy()

In [62]:
array = np.full_like(np_df, fill_value=0)

In [63]:
print(array)

[[0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 ...
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]]


In [64]:
print(array.shape)

(418, 6)


*Array filled with all one

In [31]:
arn = np.full([2,3], 1, dtype=int)

In [65]:
print(arn)

[[1 1 1]
 [1 1 1]]


In [66]:
array2 = np.full_like(np_df, fill_value=1)

In [67]:
array2

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       ...,
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]])

In [68]:
print(array2.shape)

(418, 6)


*Replace the elements that don't satisfy a given condition

In [72]:
np_df = df.to_numpy()

In [75]:
np_df

array([[8.92000e+02, 0.00000e+00, 3.00000e+00, 0.00000e+00, 0.00000e+00,
        7.82920e+00],
       [8.93000e+02, 1.00000e+00, 3.00000e+00, 1.00000e+00, 0.00000e+00,
        7.00000e+00],
       [8.94000e+02, 0.00000e+00, 2.00000e+00, 0.00000e+00, 0.00000e+00,
        9.68750e+00],
       ...,
       [1.30700e+03, 0.00000e+00, 3.00000e+00, 0.00000e+00, 0.00000e+00,
        7.25000e+00],
       [1.30800e+03, 0.00000e+00, 3.00000e+00, 0.00000e+00, 0.00000e+00,
        8.05000e+00],
       [1.30900e+03, 0.00000e+00, 3.00000e+00, 1.00000e+00, 1.00000e+00,
        2.23583e+01]])

In [80]:
condition = np_df%2==0
np_df[~condition] = 2

In [81]:
print(np_df)

[[ 892.    0.    2.    0.    0.    2.]
 [   2.    2.    2.    2.    0.    2.]
 [ 894.    0.    2.    0.    0.    2.]
 ...
 [   2.    0.    2.    0.    0.    2.]
 [1308.    0.    2.    0.    0.    2.]
 [   2.    0.    2.    2.    2.    2.]]


*To get the maximum value from a matrix

In [82]:
max_value= np.max(np_df)

In [83]:
print(max_value)

1308.0
