Task 2

In [16]:
# Task 2 (i) Reading and Writing from a file
# to read from file1
file1=open("File1.txt","r")
data=file1.read()
# to write in file2

file2=open("File2.txt","w")
file2.write(data)
# closing the file objects
file1.close()
file2.close()


# Task 2 (ii)  To write a dictionary in a file 
dict={
    "name":"Sanjeet Raj",
    "roll":2306009,
    "language":"python"
}

# using pickle 
import pickle
file3=open("File3.txt","wb")

pickle.dump(dict,file3)
file3.close()

# normally
file3=open("File3.txt","w")
file3.write("{")
for i in dict:
    text=str(i)+":"+str(dict[i])+","
    file3.write(text)
file3.write("}")
file3.close()


# Task 2 (iii) Finding the size of a file
import os
f=os.path.getsize("./File1.txt")
print("Size of the given file:",f)


# Task 2 (iv) Most repeated word

file1=open("File1.txt","r")
str1=""
data=file1.read()
file1.close()
for i in range(len(data)):
    if(not(data[i].isalnum())):
        str1=str1+" "
    else:
        str1+=data[i]
array=str1.split(None)

wordDict={}
for i in array :
    if i in wordDict:
        wordDict[i]+=1
    else:
        wordDict[i]=1
max=0
lWord=""
for i in wordDict:
    if wordDict[i]>max:
        max=wordDict[i]
        lWord=i

print("Most repeated word in file:",lWord,"\t\t freq:",max,"times")


# Task 2 (v) Read Specific Lines from a file
file1=open("File1.txt","r")
data=file1.readlines()
file1.close()
index=int(input("Enter the line number to read:"))
print(f"line at line number {index} is ")
print(data[index-1])



Size of the given file: 128
Most repeated word in file: is 		 freq: 2 times
line at line number 1 is 
This is the first file .



Task 3

In [17]:
import numpy as np


In [18]:
# 1.Create an empty and full array
# Empty array
nums1=np.empty(9)
nums1

array([5.34050071e-310, 0.00000000e+000, 0.00000000e+000, 0.00000000e+000,
       0.00000000e+000, 0.00000000e+000, 0.00000000e+000, 0.00000000e+000,
       0.00000000e+000])

In [19]:
# Full array
nums2=np.full((1,6),23)
nums2

array([[23, 23, 23, 23, 23, 23]])

In [20]:
# 2.Array with all zeroes
numsZeroes=np.zeros((3,3))
numsZeroes

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [21]:
# 4.Replace numpy array elements that does not follow a given condition

nums5=np.arange(11,38,3).reshape(3,3)
# before replacement
nums5

array([[11, 14, 17],
       [20, 23, 26],
       [29, 32, 35]])

In [22]:
# Condition :elements divisible by 2
cond=nums5%2==0
# Replacing all the elements which are not divisible by two with nan
nums5=np.where(cond,nums5,np.nan)
nums5

array([[nan, 14., nan],
       [20., nan, 26.],
       [nan, 32., nan]])

In [23]:
# Condition :elements divisible by 2
cond=nums5%2==0
# Replacing all the elements which are not divisible by two with nan
nums5=np.where(cond,nums5,np.nan)
nums5

array([[nan, 14., nan],
       [20., nan, 26.],
       [nan, 32., nan]])

In [24]:
# 3.Array with all ones
numsOnes=np.ones((3,3),dtype=int)
numsOnes

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

Task 4

In [25]:
#Task4
import pandas as pd

In [26]:
df=pd.read_csv("./Student Degree College Data.csv")

In [27]:
df.head()


form_no             name category minority gender  hs_total  hs_pass_year  \
0  1801371  Susmita Bhowmik       UR       NO      F       381          2018   
1  1803096        Ankur Das       SC       NO      M       262          2018   
2  1801287   Rashmita Tanti       UR       NO      M       278          2018   
3  1803173     Sanjib Ghosh       UR       NO      M       194          2018   
4  1801077      Swarupa Pal       UR       NO      F       320          2015   

   first_choice_sub  first_choice_marks second_choice_sub  \
0       Mathematics                  80       Mathematics   
1         Education                  61           Bengali   
2  Human Physiology                  74            Botany   
3               NaN                   0               NaN   
4               NaN                   0               NaN   

   second_choice_marks first_choice_stream second_choice_stream  
0                   80    Physical Science     Physical Science  
1                   58                Arts                 Arts  
2                   74         Bio Science          Bio Science  
3                    0                Arts                 Arts  
4                    0         Bio Science          Bio Science

In [28]:
# 1Split a column in pandas dataframe and get a part of it
fname=df["name"].str.split(" ").str[0].to_list()
fname

['Susmita',
 'Ankur',
 'Rashmita',
 'Sanjib',
 'Swarupa',
 'Abhijit',
 'Susmita',
 'Snehabrata',
 'Bijan',
 'Supratip',
 'Tania',
 'Paramita',
 'Abhik',
 'Naina',
 'Paulami',
 'Anirban',
 'Sudrip',
 'Parmita',
 'Biswambar',
 'Shayal',
 'Koshik',
 'Sauratabha',
 'Lalanjoy',
 'Silvana',
 'Moumita',
 'Mousumi',
 'Saini',
 'Rupanjali',
 'Ankita',
 'Balai',
 'Prasanta',
 'Dwipjyoti',
 'Akash',
 'Snigdha',
 'Pritam',
 'Deep',
 'Sumit',
 'Sneha',
 'Rohini',
 'Tanik',
 'Oishi',
 'Sayan',
 'Sushrita',
 'Rahul',
 'Sarita',
 'Sagarika',
 'Nabarun',
 'Supratim',
 'Puja',
 'Arpita',
 'Mijanur',
 'Sarbani',
 'Kishan',
 'Amit',
 'Sipan',
 'Habibur',
 'Gagan',
 'Surmista',
 'Saoli',
 'Swarup',
 'Soumyadip',
 'Krishan',
 'Baishali',
 'Debajit',
 'Shuhardha',
 'Rikta',
 'Saptadipa',
 'Rimisoma',
 'Sujan',
 'Manish',
 'Bidisha',
 'Ramprasad',
 'Santanu',
 'Poulami',
 'Krishna',
 'Arpita',
 'Trisha',
 'Monalisa',
 'Anirban',
 'Tanusri',
 'Soma',
 'Twinkel',
 'Dibyendu',
 'Diptanu',
 'Arpita',
 'Tapas',
 '

In [29]:
# 2Return the Index label if some condition is satisfied over a column in Pandas Dataframe
indexs=df[df["hs_pass_year"]>2017].index.to_list()
indexs

[0,
 1,
 2,
 3,
 5,
 6,
 7,
 8,
 9,
 10,
 11,
 12,
 13,
 14,
 15,
 16,
 17,
 18,
 19,
 20,
 21,
 22,
 23,
 24,
 25,
 26,
 27,
 28,
 29,
 30,
 31,
 32,
 35,
 36,
 37,
 38,
 39,
 40,
 41,
 42,
 43,
 44,
 45,
 46,
 47,
 48,
 49,
 50,
 51,
 52,
 53,
 54,
 55,
 56,
 57,
 58,
 59,
 60,
 61,
 62,
 63,
 64,
 65,
 66,
 68,
 69,
 70,
 71,
 72,
 73,
 74,
 75,
 76,
 77,
 78,
 79,
 80,
 81,
 82,
 83,
 84,
 85,
 86,
 87,
 88,
 89,
 90,
 91,
 92,
 93,
 94,
 95,
 96,
 97,
 98,
 99,
 100,
 101,
 102,
 104,
 105,
 106,
 107,
 108,
 109,
 110,
 111,
 112,
 113,
 114,
 115,
 116,
 117,
 118,
 119,
 120,
 121,
 122,
 123,
 124,
 125,
 126,
 127,
 128,
 129,
 130,
 131,
 132,
 133,
 134,
 135,
 136,
 137,
 138,
 139,
 140,
 141,
 143,
 144,
 145,
 146,
 147,
 148,
 150,
 152,
 153,
 154,
 155,
 156,
 157,
 159,
 160,
 161,
 163,
 164,
 165,
 166,
 167,
 168,
 169,
 170,
 171,
 172,
 173,
 174,
 175,
 176,
 177,
 178,
 179,
 180,
 181,
 182,
 183,
 184,
 185,
 186,
 187,
 188,
 189,
 190,
 191,
 192,
 193,
 

In [30]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5143 entries, 0 to 5142
Data columns (total 13 columns):
 #   Column                Non-Null Count  Dtype 
---  ------                --------------  ----- 
 0   form_no               5143 non-null   int64 
 1   name                  5143 non-null   object
 2   category              5143 non-null   object
 3   minority              5143 non-null   object
 4   gender                5143 non-null   object
 5   hs_total              5143 non-null   int64 
 6   hs_pass_year          5143 non-null   int64 
 7   first_choice_sub      3602 non-null   object
 8   first_choice_marks    5143 non-null   int64 
 9   second_choice_sub     3602 non-null   object
 10  second_choice_marks   5143 non-null   int64 
 11  first_choice_stream   5143 non-null   object
 12  second_choice_stream  5143 non-null   object
dtypes: int64(5), object(8)
memory usage: 522.5+ KB


In [31]:
# 3 Drop rows from the dataframe based on certain condition applied on a column
# Drop the rows where first_choice_marks=0
df=df.drop(df[df["first_choice_marks"]==0].index,axis=0)
df


form_no                  name category minority gender  hs_total  \
0     1801371       Susmita Bhowmik       UR       NO      F       381   
1     1803096             Ankur Das       SC       NO      M       262   
2     1801287        Rashmita Tanti       UR       NO      M       278   
7     1801105   Snehabrata Dasgupta       UR       NO      M       327   
8     1800886      Bijan Sankar Das       SC       NO      M       363   
...       ...                   ...      ...      ...    ...       ...   
5056  1824153     Mesak Lalmuanfela       ST       NO      M       298   
5057  1824486     Ratul Chakraborty       UR       NO      M       415   
5058  1812856            Rahul Paul       UR       NO      M       373   
5059  1822484  Sutapa Modak Bhowmik       UR       NO      F       337   
5142      501         Jayatri Datta       UR       NO      F       368   

      hs_pass_year  first_choice_sub  first_choice_marks second_choice_sub  \
0             2018       Mathematics                  80       Mathematics   
1             2018         Education                  61           Bengali   
2             2018  Human Physiology                  74            Botany   
7             2018         Chemistry                  78           Zoology   
8             2018           Physics                  80         Chemistry   
...            ...               ...                 ...               ...   
5056          2016           English                  74           English   
5057          2018           Physics                  85           Physics   
5058          2018  Human Physiology                  84            Botany   
5059          2018           Zoology                  56           Zoology   
5142          2018         Sociology                  86         Sociology   

      second_choice_marks first_choice_stream second_choice_stream  
0                      80    Physical Science     Physical Science  
1                      58                Arts                 Arts  
2                      74         Bio Science          Bio Science  
7                      78    Physical Science          Bio Science  
8                      74    Physical Science     Physical Science  
...                   ...                 ...                  ...  
5056                   74                Arts                 Arts  
5057                   85    Physical Science     Physical Science  
5058                   84         Bio Science     Physical Science  
5059                   56         Bio Science          Bio Science  
5142                   86                Arts                 Arts  

[3566 rows x 13 columns]

Task 5

In [32]:
#How to get list of parameters name from a function in Python
import inspect 
import numpy as np
print(inspect.signature(np.linspace))

# How to Print Multiple Arguments in Python

def func(*args,**kwargs):
    for i in args:
        print(i)
    for j in kwargs:
        print(f"{j}:{kwargs[j]}")
func(2,3,name="nobody",hobby="code")

# Python program to find the power of a number using recursion
def pow(num,power):
    if power==0:
        return 1
    return num*pow(num,power-1)
print(f"5 raised to power 3={pow(5,3)}")

(start, stop, num=50, endpoint=True, retstep=False, dtype=None, axis=0)
2
3
name:nobody
hobby:code
5 raised to power 3=125
