# Task2

In [28]:
contents=[]
with open('sample_text1.txt','r') as file:
    for line in file:
        print(line,end=' ')
        contents.append(line)

hello hello hello heelo
 python pithon pygon
 python python python python 

In [29]:
contents

['hello hello hello heelo\n',
 'python pithon pygon\n',
 'python python python python']

In [30]:
contents2=[]
with open('sample_text2.txt','r') as file:
    for line in file:
        print(line,end=' ')
        contents2.append(line)

I'm going to write into this 

In [31]:
with open('sample_text2.txt','a') as file:
    file.write('\n')
    for line in contents:
        file.write(line)

In [32]:
contents2=[]
with open('sample_text2.txt','r') as file:
    for line in file:
        print(line,end=' ')
        contents2.append(line)

I'm going to write into this
 hello hello hello heelo
 python pithon pygon
 python python python python 

In [33]:
#to find file size
import os
file_path='sample_text1.txt'
file_size=os.path.getsize(file_path)
print(f'File size in bytes:{file_size}')

File size in bytes:71


In [34]:
lines_to_read=[1,2]

To read specific lines:

In [35]:
with open('sample_text1.txt', 'r') as file1:
    for line_no,line_text in enumerate(file1,start=1):
        if line_no in lines_to_read:
            print(f'The text in line {line_no} is {line_text}')

The text in line 1 is hello hello hello heelo

The text in line 2 is python pithon pygon



To find most common word:

In [36]:
import pandas as pd

In [39]:
with open('sample_text1.txt','r') as file1:
    words=file1.read().split()
w_Series=pd.Series(words)

In [46]:
common=w_Series.value_counts()

In [48]:
common.index[0] #most common word

'python'

In [50]:
diction={'hello':1,'mangrove':2,'zeph':3}

In [51]:
import json
with open('sample.json','a+') as file:
    json.dump(diction,file)

In [54]:
with open('sample.json','r') as file:
    print(json.load(file))

{'hello': 1, 'mangrove': 2, 'zeph': 3}


# Task3

In [1]:
import numpy as np

In [15]:
arr1=np.array([1,2,3,4,5,6])
#To create a full array of specific shape and fill with a specific value
arr3=np.full(shape=(3,3),fill_value=7)

In [3]:
arr1

array([1, 2, 3, 4, 5, 6])

In [16]:
arr3

array([[7, 7, 7],
       [7, 7, 7],
       [7, 7, 7]])

In [10]:
type(arr1)

numpy.ndarray

In [13]:
arr2=np.empty((1,6),)

In [19]:
arr2 #filled with random values

array([[2.7210493e-316, 0.0000000e+000, 5.8025718e-317, 5.8025718e-317,
        5.7635959e-317, 5.7754337e-317]])

In [20]:
arr4=np.zeros((3,3))
arr5=np.ones((3,3))

In [23]:
arr4 #default data type is float can change it

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [22]:
arr5

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [29]:
arr6=np.where(arr1>3,arr1,0)
arr6
#It keeps the arr elements that satisfies the given condtions and replaces the ones that don't satisfy with zero .. much like the ternary function

array([0, 0, 0, 4, 5, 6])

In [31]:
arr7=arr1.reshape((2,3))
arr7

array([[1, 2, 3],
       [4, 5, 6]])

In [32]:
np.max(arr7)
#To get maximum value of a matrix

6

# Task 4

In [17]:
import pandas as pd
import numpy as np

In [18]:
#df=pd.DataFrame(data=np.random.rand(10,3),columns=['Feature1','Feature2','Feature3'])
#don't run it twice

In [19]:
df

Feature1  Feature2  Feature3
0  0.882603  0.191026  0.021996
1  0.679203  0.867745  0.866258
2  0.712027  0.502142  0.165822
3  0.873412  0.187734  0.552652
4  0.847340  0.962426  0.660890
5  0.213306  0.572916  0.505553
6  0.491513  0.283469  0.369442
7  0.579188  0.669197  0.259585
8  0.245683  0.173058  0.094537
9  0.631961  0.381867  0.832041

In [20]:
#To split a column----we're splitting Feature1
df[df['Feature1']>0.3]['Feature1']


0    0.882603
1    0.679203
2    0.712027
3    0.873412
4    0.847340
6    0.491513
7    0.579188
9    0.631961
Name: Feature1, dtype: float64

In [21]:
#to return the index label
df[df['Feature1']>0.3].index

Index([0, 1, 2, 3, 4, 6, 7, 9], dtype='int64')

In [35]:
#to drop rows based on a certain condition
index_of_rows_to_drop=df[df['Feature1']>0.7].index

In [36]:
index_of_rows_to_drop

Index([0, 2, 3, 4], dtype='int64')

In [37]:
df.drop(index_of_rows_to_drop,axis=0)

Feature1  Feature2  Feature3
1  0.679203  0.867745  0.866258
5  0.213306  0.572916  0.505553
6  0.491513  0.283469  0.369442
7  0.579188  0.669197  0.259585
8  0.245683  0.173058  0.094537
9  0.631961  0.381867  0.832041

In [38]:
df1=df
df1

Feature1  Feature2  Feature3
0  0.882603  0.191026  0.021996
1  0.679203  0.867745  0.866258
2  0.712027  0.502142  0.165822
3  0.873412  0.187734  0.552652
4  0.847340  0.962426  0.660890
5  0.213306  0.572916  0.505553
6  0.491513  0.283469  0.369442
7  0.579188  0.669197  0.259585
8  0.245683  0.173058  0.094537
9  0.631961  0.381867  0.832041

In [41]:
df1=df1.set_index('Feature1')

In [42]:
df1

Feature2  Feature3
Feature1                    
0.882603  0.191026  0.021996
0.679203  0.867745  0.866258
0.712027  0.502142  0.165822
0.873412  0.187734  0.552652
0.847340  0.962426  0.660890
0.213306  0.572916  0.505553
0.491513  0.283469  0.369442
0.579188  0.669197  0.259585
0.245683  0.173058  0.094537
0.631961  0.381867  0.832041

In [44]:
df1[df1['Feature2']>0.6].index

Index([0.6792034245670601, 0.8473400423178544, 0.5791876689624775], dtype='float64', name='Feature1')

# Task5

In [2]:
import seaborn as sns

In [3]:
import inspect

## 1. To get the parameters

In [4]:
params=inspect.signature(sns.countplot).parameters
params=list(params)

In [5]:
params

['data',
 'x',
 'y',
 'hue',
 'order',
 'hue_order',
 'orient',
 'color',
 'palette',
 'saturation',
 'fill',
 'hue_norm',
 'stat',
 'width',
 'dodge',
 'gap',
 'log_scale',
 'native_scale',
 'formatter',
 'legend',
 'ax',
 'kwargs']

## 3. To print power of a number using recursion

In [6]:
result=1

In [8]:
def power(num,exp):
    if exp==0:
        return 1
    return power(num,exp-1)*num

In [9]:
power(2,3)

8

## 2. To print multiple arguments 

In [14]:
#To print the arguments passed to a function:
def fun(*args,**kwargs):
    #args=arguments (not in any order)
    #kwargs=keyword arguments (in any order)
    for arg in args:
        print(f'arg: {arg}')
    for key,arg in kwargs.items():
        print(f'key: {key} arg: {arg}')

In [15]:
fun(1,2,3,a=4,c=9,b=4)

arg: 1
arg: 2
arg: 3
key: a arg: 4
key: c arg: 9
key: b arg: 4
