Task_2


In [ ]:
#Task2
#1.Read content from a file and write it into another one.
f1=open("_File1.txt","r")
content=f1.readlines()
for i in content:
    print(i)
f2=open("./_File2.txt","w")
f2.write(content)

f1.close
f2.close

#2.To write a dictionary in a file

dict={
    "college":"NITP","city":"Patna","country":"India"
}
with open("_File1.txt", 'w') as f1:
    for key, value in dict.items():
        f1.write('%s:%s\n' % (key, value))
        f1.close()


#3.Find size of a file in python

import os
f= os.path.getsize("./_File1.txt")
print(" Size of file is :",f)

#4.Find the most repeated word in a file

file = open("_File1.txt","r")
repeat = ""
freq = 0
words = []

for line in file:
	line_word = line.lower().replace(',','').replace('.','').split(" ");
	for w in line_word:
		words.append(w);
for i in range(0, len(words)):
	count = 1;
	for j in range(i+1,len(words)):
		if(words[i]==words[j]):
			count=count + 1;
	if(count > freq):
		freq=count;
		repeat=words[i];
print("Most repeated word: "+repeat)
print("Frequency: "+str(freq))
file.close();

#5.Read specific Lines from a file

f=open("_File1.txt","rt")
content=file.readlines()
print("fifth line")
print(content[4])
print("first five lines")
print(content[0:5])

Task_3


In [1]:
import numpy as np
import pandas as pd

In [2]:
#1.Create an empty and a full Numpy array

a=np.empty([5,3])
print("Empty Array")
print(a)

b= np.full([3,3],45)
print("\n Full Array")
print(b)

Empty Array
[[5.04741622e-310 0.00000000e+000 2.10077583e-312]
 [6.79038654e-313 2.22809558e-312 2.14321575e-312]
 [2.35541533e-312 6.79038654e-313 2.22809558e-312]
 [2.14321575e-312 2.46151512e-312 2.41907520e-312]
 [5.97819431e-322 6.01347002e-154 6.32404027e-322]]

 Full Array
[[45 45 45]
 [45 45 45]
 [45 45 45]]


In [3]:
#2.Create a numpy array filled with all zeros
c=np.zeros([3,3],dtype=int)
print(c)

[[0 0 0]
 [0 0 0]
 [0 0 0]]


In [4]:
#3.Create a numpy array  filled with all ones
d=np.ones([3,5],dtype=int)
print(d)

[[1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]]


In [5]:
#4.Replace Numpy array elements that don't satisfy a given condition
e=np.array([10,28,38,90,45,23,67,43,79])
print("given array is:")
print(e)
print("modified array:")
for x in e:
 if x%2!=0:
   x=x-1
   print(x,end=" ")
 else:
   print(x,end=" ")


given array is:
[10 28 38 90 45 23 67 43 79]
modified array:
10 28 38 90 44 22 66 42 78 

In [6]:
#5.Find the maximum value from the matrix
f=np.matrix('[1,2,3;2,3,4;3,4,5]')
g=f.max()
print("maximum number is:")
print(g)

maximum number is:
5


Task_4


In [7]:
df=pd.read_csv('/content/archive.zip')
df.head()

#1.Split a column in pandas DataFrame and get part of it.
df['Gender'].str.split(', ', expand=True)

df.iloc[4:8,0:14]

#2.Return the index label if some condition is satisfied over a pandas column datafame
new_df=df[df['Age']>32]
new_df

#3.Drop rows from dataframe based on certain condition applied on column
a= df[(df['Age']>=15) & (df['Age']<=30)].index
df.drop(a,inplace=True)
df.head(15)

Age  Gender     Marital Status      Occupation   Monthly Income  \
37    32  Female  Prefer not to say      House wife        No Income   
58    31    Male            Married        Employee  More than 50000   
99    32  Female            Married      House wife        No Income   
116   31  Female            Married      House wife        No Income   
118   32  Female            Married        Employee   25001 to 50000   
123   32    Male            Married        Employee  More than 50000   
131   32  Female            Married        Employee  More than 50000   
137   33    Male            Married        Employee  More than 50000   
148   32    Male            Married        Employee   10001 to 25000   
157   32  Female            Married      House wife        No Income   
184   32  Female            Married      House wife        No Income   
189   31    Male            Married  Self Employeed  More than 50000   
192   31  Female            Married        Employee  More than 50000   
215   32    Male            Married  Self Employeed   10001 to 25000   
218   31  Female            Married      House wife        No Income   

    Educational Qualifications  Family size  latitude  longitude  Pin code  \
37                    Graduate            5   12.9820    77.6256    560008   
58                        Ph.D            5   12.9119    77.6446    560102   
99                  Uneducated            3   13.0140    77.5658    560012   
116                     School            5   13.0289    77.5400    560022   
118                   Graduate            5   12.9261    77.6221    560034   
123                       Ph.D            5   12.9635    77.5821    560002   
131                   Graduate            1   13.0019    77.5713    560003   
137                       Ph.D            5   12.9980    77.6227    560005   
148                   Graduate            4   12.9783    77.6408    560038   
157                   Graduate            3   12.9850    77.5533    560010   
184                     School            5   12.9889    77.5741    560020   
189                     School            6   13.0487    77.5923    560024   
192                       Ph.D            5   12.9662    77.6068    560025   
215                     School            3   12.9820    77.6256    560008   
218                   Graduate            5   13.0078    77.5577    560055   

    Output   Feedback Unnamed: 12  
37     Yes  Negative          Yes  
58     Yes   Positive         Yes  
99      No   Positive          No  
116    Yes   Positive         Yes  
118    Yes   Positive         Yes  
123    Yes  Negative          Yes  
131     No   Positive          No  
137     No  Negative           No  
148    Yes   Positive         Yes  
157    Yes   Positive         Yes  
184    Yes   Positive         Yes  
189    Yes   Positive         Yes  
192    Yes   Positive         Yes  
215    Yes  Negative          Yes  
218    Yes   Positive         Yes

Task_5


In [ ]:
import inspect
def play(a, b):
    return a**b

print(inspect.signature(play))

#How to Print Multiple Arguments in Python?
def arguments(a,b):
    print(a+" "+b)
arguments("name", "college")

#Python program to find the power of a number using recursion
def power(n,p):
    if p==0:
        return 1
    else:
        return n*(power(n,p-1))

base = float(input("Enter value of base: "))
exponent = int(input("Enter value of exponent: "))
result = power(base, exponent)
print("Result is:", result)

(a, b)
name college
